import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google'
import "./globals.css";

const dm_sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "GoArta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <div className="relative">
          {/* Background div */}
          <div
            className="fixed inset-0 bg-center z-0 bg-repeat"
            style={{
              backgroundImage: `url('/grid_bg.jpg')`,
              opacity: "0.5",
              backgroundSize: "40%"
            }}
          />
          
          {/* Content wrapper */}
          <div className="relative z-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
