import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/AuthContext";
import Script from "next/script";   // ✅

export const metadata: Metadata = {
  title: "GoArta",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <AuthProvider>
          <div className="relative">
            {/* Background div */}
            <div
              className="fixed inset-0 bg-center z-0 bg-repeat"
              style={{
                backgroundImage: `url('/grid_bg.jpg')`,
                opacity: "0.5",
                backgroundSize: "40%"
              }}
            />

            <div
              className="fixed inset-0 bg-center z-0"
              style={{
                background: "linear-gradient(90deg, #FFFFFF, #F5F5F5, #E0E0E0)",
                opacity: "0.5",
              }}
            />

            {/* Content wrapper */}
            <div className="relative z-10">
              {children}
            </div>
          </div>
        </AuthProvider>

        {/* ✅ Razorpay SDK loader */}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
